# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "kv-test"
client_id = "c23aef6c76b38267eae26c983dbad094"
application_url = "https://modern-numerical-journalism-burlington.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://modern-numerical-journalism-burlington.trycloudflare.com/auth/callback",
  "https://modern-numerical-journalism-burlington.trycloudflare.com/auth/shopify/callback",
  "https://modern-numerical-journalism-burlington.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kv-empty-store.myshopify.com"
